name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'

    - name: Enable bundler cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Upgrade Bundler
      run: |
        gem uninstall bundler -a -x || true
        gem install bundler -v 2.4.22

    - name: Install deps
      run: |
        bundle _2.4.22_ config set path vendor/bundle
        bundle _2.4.22_ install --jobs 4 --retry 3
        npm install -g mermaid.cli

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"
          echo "NO_PUSH=--no-push" >> "$GITHUB_OUTPUT"
          echo "Pull request detected. NO_PUSH set."
        elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
          echo "Push to branch detected."
        fi

        echo "DEPLOY_BRANCH=gh-pages" >> "$GITHUB_OUTPUT"
        echo "Deployment target: gh-pages"

    - name: Debug outputs
      run: |
        echo "SRC_BRANCH=${{ steps.setup.outputs.SRC_BRANCH }}"
        echo "DEPLOY_BRANCH=${{ steps.setup.outputs.DEPLOY_BRANCH }}"
        echo "NO_PUSH=${{ steps.setup.outputs.NO_PUSH }}"

    - name: Deploy website
      run: |
        DEPLOY_CMD="yes | bin/deploy --verbose --src '${{ steps.setup.outputs.SRC_BRANCH }}' --deploy '${{ steps.setup.outputs.DEPLOY_BRANCH }}'"
        if [ -n "${{ steps.setup.outputs.NO_PUSH }}" ]; then
          DEPLOY_CMD="$DEPLOY_CMD ${{ steps.setup.
